// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsmHbvJihL_XwYxensFmxys2MfWDz3c2E',
    appId: '1:586467288112:web:f70ac5591dde3a8db3f9f5',
    messagingSenderId: '586467288112',
    projectId: 'kigalidirectoryapp',
    authDomain: 'kigalidirectoryapp.firebaseapp.com',
    storageBucket: 'kigalidirectoryapp.firebasestorage.app',
    measurementId: 'G-ZWR0SWF9T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1ABwsNYomsaD3V7eWuaFuYpRjjBQ7Eg',
    appId: '1:586467288112:android:667f6f7ff9218647b3f9f5',
    messagingSenderId: '586467288112',
    projectId: 'kigalidirectoryapp',
    storageBucket: 'kigalidirectoryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsBKT1Ug0YjWLGrpW3ZqMo-DetfW2Q8Sc',
    appId: '1:586467288112:ios:26ed7d4856df8953b3f9f5',
    messagingSenderId: '586467288112',
    projectId: 'kigalidirectoryapp',
    storageBucket: 'kigalidirectoryapp.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsBKT1Ug0YjWLGrpW3ZqMo-DetfW2Q8Sc',
    appId: '1:586467288112:ios:26ed7d4856df8953b3f9f5',
    messagingSenderId: '586467288112',
    projectId: 'kigalidirectoryapp',
    storageBucket: 'kigalidirectoryapp.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsmHbvJihL_XwYxensFmxys2MfWDz3c2E',
    appId: '1:586467288112:web:df03c22829ba4c8eb3f9f5',
    messagingSenderId: '586467288112',
    projectId: 'kigalidirectoryapp',
    authDomain: 'kigalidirectoryapp.firebaseapp.com',
    storageBucket: 'kigalidirectoryapp.firebasestorage.app',
    measurementId: 'G-FTT12FV8VW',
  );
}
